### ISSUE TITLE
Cocoa pods AWS Compilation issue

### ISSUE THREAD

**Issue by SteffeyDev** [SquaredTiki/Dringend-Issues#102]
When compiling using Dringend, I get the error:

`use of private header from outside its module: 'AWSEXTScope.h'`

The same project compiles fine in Xcode, and the projects are synced over Dropbox.  With some investigation, I found that I can get this same error in Xcode (along with many others) if I remove the Pods/Header directory completely.  I have use_frameworks! enabled in my Podfile, which allows me to use Pods in my swift project.  Thank you in advance for your assistance.

**Comment by SquaredTiki** [comment]
@SteffeyDev Very sorry about the long delay in getting back to you, it seems the GitHub notification for this slipped through the net! Unfortunately CocoaPods aren't 100% reliable over Dropbox due to the fact they don't add all the files they need to the Xcode project.

Would you be able to try importing the project through a git repo to see if you have more success?
