### ISSUE TITLE
Git and SVN support

### ISSUE THREAD

**Issue by idoodler** [SquaredTiki/Dringend-Issues#27]
It would be real cool if you can integrate Git and SVN support and a Diff like function:)

**Comment by SquaredTiki** [comment]
Definitely a well requested feature, hope to implement in the near future.

**Comment by adamstener** [comment]
This is a must have for me, but it will also make your product a must buy when it's finished!  Any idea on the timeline for this?

**Comment by SquaredTiki** [comment]
Git support is in the works and beta testers will be receiving the first build of 1.2 with Git support very soon.

Josh (📱)

**Comment by adamstener** [comment]
Any chance of becoming a beta tester?

Adam

**Comment by SquaredTiki** [comment]
You can sign up here to put yourself forward as wanting to beta test: http://tflig.ht/1aPMZiJ

**Comment by alexsikora** [comment]
Out of curiosity, can this be used for building instead of sending a zip file, for slow/limited internet connections on the iOS device? Simply push it up from the app and then inform the constructor app to pull the latest from a particular branch?

**Comment by SquaredTiki** [comment]
@alexsikora That would be possible but that's verging more onto the side of CI and what Xcode Bots are capable of doing. I shall bear it in mind though.

**Comment by alexsikora** [comment]
@SquaredTiki To be more specific, for larger projects the zip-and-send method doesn't seem very scalable? Also if you're on a network connection, sending a tiny git changeset instead of a full project file seems a lot more efficient. You could have the user configure what git commands they would want to run on a build-command. It's not really CI as it's not doing testing or constantly monitoring and such, it's just a lighter-weight way of triggering a build on new data.

**Comment by SquaredTiki** [comment]
@alexsikora It would be a good method to reduce data transfer as you said in the case of larger projects. If you could further explain what you mean by 

> You could have the user configure what git commands they would want to run on a build-command.

that would be great. That's true and it is, were you thinking that the build results would then be automatically communicated back to Dringend as soon as a push occurred from within Dringend?
