### ISSUE TITLE
Code signing is required for product type Framework in SDK 'iOS8.0'

### ISSUE THREAD

**Issue by lmumar** [SquaredTiki/Dringend-Issues#79]
Hello,

I have a project that is currently composed of iOS 8 Frameworks so that I can reuse some parts of my code in extensions. My project is structured with the following components:
- d30ish - contains the UI
- d30ishKit (Framework) - contains my application data models and shared helper codes

The project compiles fine in Xcode 6.0 but fails to compile in dringend with the following error:
- Provisioning profile does not match the bundle identifier: The provisioning profile specified in your build settings (ios team provisioning profile: com.garajeapps.d30ish) has an apple id "com.garajeapps.d30ish" which does not match your bundle identifier "com.garajeapps.d30ishKit"
- Code signing is required for product type Framework

Problem is you can only specify one provisioning profile in the constructor app, is there a workaround?

Thanks

**Comment by SquaredTiki** [comment]
Hi there,

Unfortunately at present you can only specify one provisioning profile. However, have you tried using a provisioning profile with a wild card app id, such as `*` or `com.garajeapps.*` ? 

Thanks,
Josh

**Comment by lmumar** [comment]
That would mean I can no longer use push notification

**Comment by SquaredTiki** [comment]
I see. Does the project have the correct provisioning profiles set in the project settings? At the moment the choice in The Constructor overrides these, however it may be possible in the future to add an option to use those set in the individual projects themselves.

**Comment by ezhes** [comment]
I'm having a similar issue, but with simple projects. The constructor uses the incorrect profile to sign. There isn't the possibility of it being an issue with the project because the profile is a year newer than the project as well as the name of of the profile not being present in any text on the project. If you prefer I could launch a support request

**Comment by SquaredTiki** [comment]
@shusain93 The Constructor will use the profile selected in it to sign all projects (rather than the profile selected in the project which is the enhancement request here as it is necessary in some cases). You should be able to select a provisioning profile that will work with the project in The Constructor and then build the project successfully. Let me know if there are any further issues.
